### ISSUE TITLE
this.scale is not defined

### ISSUE THREAD

**Issue by Mrfunnybug** [thegauravtiwari/Home-Automation#3]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\kaush\Downloads\Home-Automation> node server.js
Server on at http://localhost:3000/
1522333267324 Available COM8
1522333267366 Connected COM8
1522333271281 Repl Initialized
>> C:\Users\kaush\Downloads\Home-Automation\server.js:26
        if(this.scale([0,100])<40)
                ^

TypeError: this.scale is not a function
    at Sensor.photoresistor.on (C:\Users\kaush\Downloads\Home-Automation\server.js:26:17)
    at emitOne (events.js:96:13)
    at Sensor.emit (events.js:188:7)
    at Sensor.<anonymous> (C:\Users\kaush\Downloads\Home-Automation\node_modules\johnny-five\lib\sensor.js:143:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
PS C:\Users\kaush\Downloads\Home-Automation>

**Comment by Mrfunnybug** [comment]
issue resolved
